services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    #volumes:
    #  - ./realms/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command:
      - start-dev
    #  - --import-realm
    environment:
      - DB_VENDOR=postgres
      - KC_DB_URL=jdbc:postgresql://kc_postgres:5432/postgres
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
    ports:
      - '8080:8080'
    depends_on:
      - kc_postgres
  kc_postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - kc_db:/var/lib/postgresql/data/

volumes:
  kc_db: